[package]
name = "llama-cu"
version = "0.0.0"
edition = "2024"

[dependencies]
cublas = { git = "https://github.com/YdrMaster/cuda-driver", rev = "1751f0a" }
operators = { git = "https://github.com/YdrMaster/operators-rs", rev = "30a518f" }
memmap2 = "0.9"
regex = "1.11"
nn = { git = "https://github.com/YdrMaster/InfiniNN", rev = "672d6c4" }
graph = { git = "https://github.com/YdrMaster/InfiniNN", rev = "672d6c4" }
ggus = { git = "https://github.com/InfiniTensor/gguf", rev = "23c362f" }
tensor = { git = "https://github.com/YdrMaster/tensor", rev = "66450a9" }
rwrc = { git = "https://github.com/YdrMaster/rwrc", rev = "3969558" }
