[package]
name = "llama-cu"
version = "0.0.0"
edition.workspace = true

[dependencies]
operators = { git = "https://github.com/YdrMaster/operators-rs", rev = "9c22154" }
tokeneer = { git = "https://github.com/InfiniTensor/tokeneer", rev = "12c2d99" }
regex.workspace = true
memmap2 = "0.9"
rand = "0.9"
smallvec = "1.15"
nn = { git = "https://github.com/YdrMaster/InfiniNN", rev = "5b3a0f8" }
graph = { git = "https://github.com/YdrMaster/InfiniNN", rev = "5b3a0f8" }
ggus = { git = "https://github.com/InfiniTensor/gguf", rev = "23c362f" }
tensor = { git = "https://github.com/YdrMaster/tensor", rev = "66450a9" }
